// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {CreditGateVault} from "../src/CreditGateVault.sol";
import {CreditGateTypes} from "../src/CreditGateTypes.sol";
import {MockERC20} from "../src/mocks/MockERC20.sol";
import {MockFtsoV2} from "../src/mocks/MockFtsoV2.sol";
import {MockFdcVerification} from "../src/mocks/MockFdcVerification.sol";

/// @title CreditGateVault GoTeeCompatTest
/// @notice Cross-language compatibility test: verifies that an EIP-191 eligibility
///         attestation signed by the Go FCC extension (TEE handler) is accepted by
///         the Solidity CreditGateVault.submitEligibility.
///
///         This is the strongest possible evidence for the FCC integration: the
///         exact signature bytes produced by the Go TEE handler are submitted to
///         the on-chain vault, which recovers the signer via ecrecover and checks
///         it equals teeAuthority.
///
/// @dev The signature below was generated by the Go handler (handler.go) with
///      signing key 0xea4e...94e4 → authority 0x9fC250f05DCEBcE837348863300d419b3B31Eb9b
///      For input: borrower=0xDE62..., limit=100e6, expiry=1893456000, nonce=0, rev=0.
///      Captured 2026-08-05 via curl POST /action (see evidence/tee-attestation.json).
contract CreditGateVaultGoTeeCompatTest is Test {
    CreditGateVault public vault;
    MockERC20 public fxrp;
    MockERC20 public usdt0;
    MockFtsoV2 public ftso;
    MockFdcVerification public fdc;

    // Go handler authority (derived from CREDITGATE_SIGNING_KEY=ea4e...94e4)
    address constant GO_TEE_AUTHORITY = 0x9fC250f05DCEBcE837348863300d419b3B31Eb9b;
    // Borrower used in the captured Go signature
    address constant BORROWER = 0xDE62c19Ed5877f91A76D9FD44a1B86837b4Dce57;

    uint256 constant COLLATERAL_RATIO_BPS = 15000;
    uint64 constant FTSO_STALENESS_LIMIT = 300;
    uint256 constant LOAN_DURATION = 30 days;

    function setUp() public {
        fxrp = new MockERC20("FlareXRP", "FXRP", 6);
        usdt0 = new MockERC20("USDT0", "USDT0", 6);
        ftso = new MockFtsoV2();
        fdc = new MockFdcVerification();

        vault = new CreditGateVault(
            address(fxrp),
            address(usdt0),
            GO_TEE_AUTHORITY, // vault trusts the Go TEE handler's key
            COLLATERAL_RATIO_BPS,
            FTSO_STALENESS_LIMIT,
            LOAN_DURATION,
            address(ftso),
            address(fdc)
        );

        fxrp.mint(BORROWER, 1000e6);
        vm.prank(BORROWER);
        fxrp.approve(address(vault), type(uint256).max);

        ftso.setValueInWei(2.5e18, uint64(block.timestamp));

        vm.prank(BORROWER);
        vault.registerXRPLAddress(keccak256("rCreditGateBorrower1"));
    }

    /// @notice The Go-signed attestation must be accepted by the Solidity vault.
    ///         Signature captured from the Go handler on 2026-08-05:
    ///         v=27, r=0xd8174e..., s=0x200618...
    function test_goTeeSignatureAccepted() public {
        // Deposit + request eligibility
        vm.startPrank(BORROWER);
        uint256 loanId = vault.depositCollateral(100e6);
        vault.requestEligibility(loanId);
        vm.stopPrank();

        // Submit the EXACT attestation signed by the Go handler
        vm.prank(BORROWER);
        vault.submitEligibility(
            loanId,
            CreditGateTypes.EligibilityAttestation({
                borrower: BORROWER,
                limit: 100e6,
                expiry: 1893456000,
                nonce: 0,
                revocationVersion: 0,
                v: 27,
                r: 0xd8174ec51b92248400a6427c43bb88fe7af37f045da8c74d2c629ce8a1cb4f00,
                s: 0x200618a0cf13cc45810fe44ee286b4ebf9237ea3f1e2460e177e056ff764d002
            })
        );

        // Loan becomes ELIGIBLE — the Go TEE signature is trusted on-chain
        assertEq(
            uint8(vault.getLoan(loanId).state),
            uint8(CreditGateTypes.LoanState.ELIGIBLE)
        );
        console.log("Go TEE signature accepted - loan state:", uint8(vault.getLoan(loanId).state));
    }

    /// @notice A signature with a tampered limit must be rejected (proves the vault
    ///         actually checks the signature, not just the presence of one).
    function test_tamperedLimitRejected() public {
        vm.startPrank(BORROWER);
        uint256 loanId = vault.depositCollateral(100e6);
        vault.requestEligibility(loanId);
        vm.stopPrank();

        // Same signature but limit bumped 100e6 → 101e6 → signature no longer matches
        vm.prank(BORROWER);
        vm.expectRevert(
            abi.encodeWithSelector(
                CreditGateTypes.InvalidEligibilitySigner.selector,
                0x10c558566D61Ba1787E5295b2DbBb2a1d9494a57, // recovered (wrong) signer
                GO_TEE_AUTHORITY // expected signer
            )
        );
        vault.submitEligibility(
            loanId,
            CreditGateTypes.EligibilityAttestation({
                borrower: BORROWER,
                limit: 101e6, // TAMPERED
                expiry: 1893456000,
                nonce: 0,
                revocationVersion: 0,
                v: 27,
                r: 0xd8174ec51b92248400a6427c43bb88fe7af37f045da8c74d2c629ce8a1cb4f00,
                s: 0x200618a0cf13cc45810fe44ee286b4ebf9237ea3f1e2460e177e056ff764d002
            })
        );
    }
}
