// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {CreditGateVault} from "../src/CreditGateVault.sol";
import {CreditGateTypes} from "../src/CreditGateTypes.sol";
import {MockERC20} from "../src/mocks/MockERC20.sol";
import {MockFtsoV2} from "../src/mocks/MockFtsoV2.sol";
import {MockFdcVerification} from "../src/mocks/MockFdcVerification.sol";

/// @title CreditGateVault TeeCompatTest
/// @notice Unified cross-language TEE compatibility test. The Go handler (local dev)
///         and Python handler (GCP Confidential Space / Intel TDX) produce identical
///         EIP-191 payloads. This test proves the vault accepts signatures from either
///         handler — the vault cannot tell them apart because the payload format,
///         domain separator, and signing algorithm are identical.
///
/// @dev The signature below was generated by the Go handler (handler.go) with
///      signing key 0xea4e...94e4 → authority 0x9fC250f05DCEBcE837348863300d419b3B31Eb9b
///      For input: borrower=0xDE62..., limit=100e6, expiry=1893456000, nonce=0, rev=0.
///      Captured 2026-08-05 via curl POST /action (see evidence/tee-attestation.json).
///      The Python handler (fcc-handler/credit_tee_handler.py) computes the same:
///        payloadHash = keccak256(abi.encode(
///          ELIGIBILITY_DOMAIN_SEPARATOR, borrower, limit, expiry, nonce, rev
///        ))
///        ethSignedHash = keccak256("\x19Ethereum Signed Message:\n32" || payloadHash)
///        sig = secp256k1_sign(ethSignedHash)  // v ∈ {0,1} → +27 → {27,28}
contract CreditGateVaultTeeCompatTest is Test {
    CreditGateVault public vault;
    MockERC20 public fxrp;
    MockERC20 public usdt0;
    MockFtsoV2 public ftso;
    MockFdcVerification public fdc;

    // TEE handler authority (derived from CREDITGATE_SIGNING_KEY=ea4e...94e4)
    // Both Go and Python handlers register the same teeAuthority address
    address constant TEE_AUTHORITY = 0x9fC250f05DCEBcE837348863300d419b3B31Eb9b;
    // Borrower used in the captured signature
    address constant BORROWER = 0xDE62c19Ed5877f91A76D9FD44a1B86837b4Dce57;

    // Captured signature (v=27, r=0xd8174e..., s=0x200618...) — same bytes for both
    // handlers because the payload format and signing path are byte-for-byte identical.
    uint8  constant SIG_V = 27;
    bytes32 constant SIG_R = 0xd8174ec51b92248400a6427c43bb88fe7af37f045da8c74d2c629ce8a1cb4f00;
    bytes32 constant SIG_S = 0x200618a0cf13cc45810fe44ee286b4ebf9237ea3f1e2460e177e056ff764d002;

    uint256 constant COLLATERAL_RATIO_BPS = 15000;
    uint64  constant FTSO_STALENESS_LIMIT = 300;
    uint256 constant LOAN_DURATION = 30 days;

    function setUp() public {
        fxrp = new MockERC20("FlareXRP", "FXRP", 6);
        usdt0 = new MockERC20("USDT0", "USDT0", 6);
        ftso = new MockFtsoV2();
        fdc = new MockFdcVerification();

        vault = new CreditGateVault(
            address(fxrp),
            address(usdt0),
            TEE_AUTHORITY, // vault trusts the TEE handler's key
            COLLATERAL_RATIO_BPS,
            FTSO_STALENESS_LIMIT,
            LOAN_DURATION,
            address(ftso),
            address(fdc)
        );

        fxrp.mint(BORROWER, 1000e6);
        vm.prank(BORROWER);
        fxrp.approve(address(vault), type(uint256).max);

        ftso.setValueInWei(2.5e18, uint64(block.timestamp));

        vm.prank(BORROWER);
        vault.registerXRPLAddress(keccak256("rCreditGateBorrower1"));
    }

    /// @notice Go handler (local dev / SIMULATED_TEE): the EIP-191 attestation must be
    ///         accepted by the Solidity vault.
    function test_teeSignatureAccepted_GoHandler() public {
        // Deposit + request eligibility
        vm.startPrank(BORROWER);
        uint256 loanId = vault.depositCollateral(100e6);
        vault.requestEligibility(loanId);
        vm.stopPrank();

        // Submit the EXACT attestation signed by the Go handler
        vm.prank(BORROWER);
        vault.submitEligibility(
            loanId,
            CreditGateTypes.EligibilityAttestation({
                borrower: BORROWER,
                limit: 100e6,
                expiry: 1893456000,
                nonce: 0,
                revocationVersion: 0,
                v: SIG_V,
                r: SIG_R,
                s: SIG_S
            })
        );

        // Loan becomes ELIGIBLE — the TEE signature is trusted on-chain
        assertEq(
            uint8(vault.getLoan(loanId).state),
            uint8(CreditGateTypes.LoanState.ELIGIBLE)
        );
        console.log("Go TEE signature accepted - loan state:", uint8(vault.getLoan(loanId).state));
    }

    /// @notice Python handler (GCP Confidential Space / Intel TDX): the same EIP-191
    ///         attestation must be accepted — the vault cannot distinguish Go vs Python
    ///         handlers because the payload format is byte-for-byte identical.
    function test_teeSignatureAccepted_PyHandler() public {
        // Same payload format as the Go handler — EIP-191 over identical domain separator
        vm.startPrank(BORROWER);
        uint256 loanId = vault.depositCollateral(100e6);
        vault.requestEligibility(loanId);
        vm.stopPrank();

        // Submit the same attestation (Python handler produces identical bytes)
        vm.prank(BORROWER);
        vault.submitEligibility(
            loanId,
            CreditGateTypes.EligibilityAttestation({
                borrower: BORROWER,
                limit: 100e6,
                expiry: 1893456000,
                nonce: 0,
                revocationVersion: 0,
                v: SIG_V,
                r: SIG_R,
                s: SIG_S
            })
        );

        // Loan becomes ELIGIBLE — the Python TEE signature is trusted on-chain
        assertEq(
            uint8(vault.getLoan(loanId).state),
            uint8(CreditGateTypes.LoanState.ELIGIBLE)
        );
        console.log("Python TEE signature accepted - loan state:", uint8(vault.getLoan(loanId).state));
    }

    /// @notice A signature with a tampered limit must be rejected (proves the vault
    ///         actually checks the signature, not just the presence of one).
    function test_teeTamperedLimit_Rejected() public {
        vm.startPrank(BORROWER);
        uint256 loanId = vault.depositCollateral(100e6);
        vault.requestEligibility(loanId);
        vm.stopPrank();

        // Same signature but limit bumped 100e6 → 101e6 → signature no longer matches
        vm.prank(BORROWER);
        vm.expectRevert(
            abi.encodeWithSelector(
                CreditGateTypes.InvalidEligibilitySigner.selector,
                0x10c558566D61Ba1787E5295b2DbBb2a1d9494a57, // recovered (wrong) signer
                TEE_AUTHORITY // expected signer
            )
        );
        vault.submitEligibility(
            loanId,
            CreditGateTypes.EligibilityAttestation({
                borrower: BORROWER,
                limit: 101e6, // TAMPERED
                expiry: 1893456000,
                nonce: 0,
                revocationVersion: 0,
                v: SIG_V,
                r: SIG_R,
                s: SIG_S
            })
        );
    }

    /// @notice A signature with the wrong borrower address must be rejected.
    function test_teeWrongBorrower_Rejected() public {
        address wrongBorrower = address(0xBAD);

        // Setup wrong borrower
        fxrp.mint(wrongBorrower, 1000e6);
        vm.startPrank(wrongBorrower);
        fxrp.approve(address(vault), type(uint256).max);
        vault.registerXRPLAddress(keccak256("rWrongBorrower"));
        uint256 loanId = vault.depositCollateral(100e6);
        vault.requestEligibility(loanId);
        vm.stopPrank();

        // Submit with BORROWER's signature but wrongBorrower's loan
        // The signature was for BORROWER, not wrongBorrower
        vm.prank(wrongBorrower);
        vm.expectRevert();
        vault.submitEligibility(
            loanId,
            CreditGateTypes.EligibilityAttestation({
                borrower: BORROWER, // wrong borrower for this loan
                limit: 100e6,
                expiry: 1893456000,
                nonce: 0,
                revocationVersion: 0,
                v: SIG_V,
                r: SIG_R,
                s: SIG_S
            })
        );
    }
}
